name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '*.md'
      - 'MAKEFILE'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with go ${{ matrix.go }}
    strategy:
      matrix:
        go: ["1.21", "stable"]
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - uses: actions/cache@v4
        with:
          path: ./bin
          key: ${{ runner.os }}-bin-${{ hashFiles('Makefile') }}
      - run: make test
      - run: git diff -s --exit-code
